name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm settings
        run: npm config set legacy-peer-deps true
      - name: install modules
        run: npm install
      - name: lint scripts
        run: npm run lint:ts:fix
      - name: lint styles
        run: npm run lint:ts:fix
      - name: unit tests
        run: npm run test:unit
      - name: build
        run: npm run build:prod
